name: apache-iotdb # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: 0.13.0 # just for humans, typically '1.2+git' or '1.3.2'
summary: Apache IoTDB v0.13.0 # 79 char long summary
description: |
  Apache IoTDB (Database for Internet of Things) is an IoT native database with high performance for data management and analysis, deployable on the edge and the cloud. Due to its light-weight architecture, high performance and rich feature set together with its deep integration with Apache Hadoop, Spark and Flink, Apache IoTDB can meet the requirements of massive data storage, high-speed data ingestion and complex data analysis in the IoT industrial fields.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  install-iotdb:
    command: bin/install_iotdb.py
    plugs:
      - network-bind
    daemon: simple

parts:
  iotdb:
    plugin: python
    source: .
  env:
    plugin: dump
    source: ./env-amd.tar.gz
